### ISSUE TITLE
Why have that amount of Releases?

### ISSUE THREAD

**Issue by lucasvazq** [asottile/python3.10#1]
That

**Comment by asottile** [comment]
it is a fork of cpython so it includes all the upstream tags

**Comment by asottile** [comment]
if you're interested in the actual commits -- check out the history of the `ubuntu/xenial` or `ubuntu/bionic` branch -- for example: https://github.com/asottile/python3.10/commits/ubuntu/bionic

**Comment by lucasvazq** [comment]
Oh bro, thanks. I had not noticed that
