### ISSUE TITLE
<joke> This tool failed for CPython :( </joke>

### ISSUE THREAD

**Issue by pablogsal** [asottile/python3.10#2]
> there's a significant amount of code which uses sys.version[:3] which will incorrectly report this as version 3.1 

Tell me about it :) 

https://github.com/python/cpython/pull/20198/commits/b4d4aef8433da2657c8d80207686124d15d32054

(From the folks doing the 3.10 branch bump)

**Comment by ambv** [comment]
#TodayInOpenSource

**Comment by asottile** [comment]
hey man, I tried: https://bugs.python.org/issue37616

TEN MONTHS AGO

**Comment by ambv** [comment]
lolsob.gif

**Comment by pablogsal** [comment]
![9e92dd8c-1f12-4426-b7ac-131dca1d294a_screenshot](https://user-images.githubusercontent.com/11718525/82277633-4a526980-9980-11ea-8e58-2d64ad59c2aa.jpg)
